service: tgif

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  role: arn:aws:iam::491150663186:role/service-role/basic.execution
  memorySize: 256
  timeout: 15

functions:
  tgif:
    handler: handler.main
    description: Japanese Holiday API
    environment:
      DEPLOY: false
      DEBUG: true
      BUCKET: jp.holidays
      YAML_FILE: source.yaml
      FILE: .csv
      EMAIL: ****@gmail.com
      EMAIL_REGION: us-east-1
      JSON_FILE: jp.json
      SEND_MAIL: false
    tags:
      type: public

package:
  exclude:
    - README.md
    - event.json
